apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailpit.fullname" . }}
spec:
  selector:
    app: {{ include "mailpit.name" . }}
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    name: http
  - port: {{ .Values.service.smtp.port }}
    targetPort: smtp
    name: smtp
